# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 768))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 241, 591))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.treeView = QtWidgets.QTreeView(self.groupBox)
        self.treeView.setObjectName("treeView")
        self.gridLayout_5.addWidget(self.treeView, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(260, 10, 481, 691))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab3)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget.addTab(self.tab3, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(750, 10, 271, 691))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(12, 32, 251, 361))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBox_4)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 229, 490))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.InputLayer = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.InputLayer.setMinimumSize(QtCore.QSize(200, 50))
        self.InputLayer.setMaximumSize(QtCore.QSize(200, 50))
        self.InputLayer.setAutoFillBackground(True)
        self.InputLayer.setAlignment(QtCore.Qt.AlignCenter)
        self.InputLayer.setObjectName("InputLayer")
        self.verticalLayout_2.addWidget(self.InputLayer)
        self.NNLayer = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.NNLayer.setMinimumSize(QtCore.QSize(200, 50))
        self.NNLayer.setMaximumSize(QtCore.QSize(200, 50))
        self.NNLayer.setAutoFillBackground(True)
        self.NNLayer.setAlignment(QtCore.Qt.AlignCenter)
        self.NNLayer.setObjectName("NNLayer")
        self.verticalLayout_2.addWidget(self.NNLayer)
        self.CNNLayer = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.CNNLayer.setMinimumSize(QtCore.QSize(200, 50))
        self.CNNLayer.setMaximumSize(QtCore.QSize(200, 50))
        self.CNNLayer.setAutoFillBackground(True)
        self.CNNLayer.setAlignment(QtCore.Qt.AlignCenter)
        self.CNNLayer.setObjectName("CNNLayer")
        self.verticalLayout_2.addWidget(self.CNNLayer)
        self.RNNLayer = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.RNNLayer.setMinimumSize(QtCore.QSize(200, 50))
        self.RNNLayer.setMaximumSize(QtCore.QSize(200, 50))
        self.RNNLayer.setAutoFillBackground(True)
        self.RNNLayer.setAlignment(QtCore.Qt.AlignCenter)
        self.RNNLayer.setObjectName("RNNLayer")
        self.verticalLayout_2.addWidget(self.RNNLayer)
        self.LSTMLayer = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.LSTMLayer.setMinimumSize(QtCore.QSize(200, 50))
        self.LSTMLayer.setMaximumSize(QtCore.QSize(200, 50))
        self.LSTMLayer.setAutoFillBackground(True)
        self.LSTMLayer.setAlignment(QtCore.Qt.AlignCenter)
        self.LSTMLayer.setObjectName("LSTMLayer")
        self.verticalLayout_2.addWidget(self.LSTMLayer)
        self.SoftmaxLayer = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.SoftmaxLayer.setMinimumSize(QtCore.QSize(200, 50))
        self.SoftmaxLayer.setMaximumSize(QtCore.QSize(200, 50))
        self.SoftmaxLayer.setAutoFillBackground(True)
        self.SoftmaxLayer.setAlignment(QtCore.Qt.AlignCenter)
        self.SoftmaxLayer.setObjectName("SoftmaxLayer")
        self.verticalLayout_2.addWidget(self.SoftmaxLayer)
        self.Optimizer = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.Optimizer.setMinimumSize(QtCore.QSize(200, 50))
        self.Optimizer.setMaximumSize(QtCore.QSize(200, 50))
        self.Optimizer.setAutoFillBackground(True)
        self.Optimizer.setAlignment(QtCore.Qt.AlignCenter)
        self.Optimizer.setObjectName("Optimizer")
        self.verticalLayout_2.addWidget(self.Optimizer)
        self.OutputLayer = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.OutputLayer.setMinimumSize(QtCore.QSize(200, 50))
        self.OutputLayer.setMaximumSize(QtCore.QSize(200, 50))
        self.OutputLayer.setAutoFillBackground(True)
        self.OutputLayer.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputLayer.setObjectName("OutputLayer")
        self.verticalLayout_2.addWidget(self.OutputLayer)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout.addWidget(self.scrollArea_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 400, 251, 291))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.groupBox_5)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 243, 263))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 630, 151, 51))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_New = QtWidgets.QAction(MainWindow)
        self.action_New.setObjectName("action_New")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_New)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.actionSave_As)
        self.menu_File.addAction(self.action_Exit)
        self.menuBar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Browser"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Model"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "New Model"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Layers"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Layer"))
        self.InputLayer.setText(_translate("MainWindow", "Input Layer"))
        self.NNLayer.setText(_translate("MainWindow", "NN Layer"))
        self.CNNLayer.setText(_translate("MainWindow", "CNN Layer"))
        self.RNNLayer.setText(_translate("MainWindow", "RNN Layer"))
        self.LSTMLayer.setText(_translate("MainWindow", "<html><head/><body><p>LSTM Layer</p></body></html>"))
        self.SoftmaxLayer.setText(_translate("MainWindow", "SoftMax Layer"))
        self.Optimizer.setText(_translate("MainWindow", "Optmizer"))
        self.OutputLayer.setText(_translate("MainWindow", "Output Layer"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Property"))
        self.pushButton.setText(_translate("MainWindow", "Save and Quit"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_New.setText(_translate("MainWindow", "&New"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_Save.setText(_translate("MainWindow", "&Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save &As"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
